# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-05 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('recreate_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'superuser',
            },
        ),
    ]
