# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-08 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endblog', '0002_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='endblog.SuperUser')),
            ],
            options={
                'db_table': 'token_user',
            },
        ),
    ]
